### ISSUE TITLE
Generate undefined.js

### ISSUE THREAD

**Issue by larsurilch** [KABBOUCHI/laravel-mix-vue3#1]
Hello my friend,

I'm using your package with Vue.js 3 and Laravel 8. When executing the **npm run dev**, the file undefined.js is generated. 
How to fix the problem ?!

Thanks!

![config](https://user-images.githubusercontent.com/251246/92629002-06bf9a80-f2a4-11ea-9517-2edb12edeb7f.png)
![result](https://user-images.githubusercontent.com/251246/92629010-09ba8b00-f2a4-11ea-8060-41e5a501be19.png)

**Comment by KABBOUCHI** [comment]
can you share ur `app.js` src file?

**Comment by larsurilch** [comment]
[package.json.zip](https://github.com/KABBOUCHI/laravel-mix-vue3/files/5196958/package.json.zip)
![app js](https://user-images.githubusercontent.com/251246/92631412-b2b6b500-f2a7-11ea-9aff-af759c6f5172.png)

**Comment by KABBOUCHI** [comment]
I was able to reproduce it, compiling css files causing this issue.

I'll try to fix it ASAP.

**Comment by larsurilch** [comment]
Thanks KABBOUCHI,
Best regards

**Comment by KABBOUCHI** [comment]
@larsurilch plz update and retry

**Comment by larsurilch** [comment]
> @larsurilch plz update and retry

Problem solved. Thanks
