### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by craigrileyuk** [KABBOUCHI/laravel-mix-vue3#6]
Given that Vue 3 is supposed to be completely tree-shakeable, I was surprised to see that even a basic 'Hello World' test weighed in at a hefty 350 KiB after being built for production.

I've only imported the createApp method from "vue" and I've not used anything else... Is one of the loaders including the full build?

**Comment by KABBOUCHI** [comment]
plz update and retry

**Comment by thecyrilcril** [comment]
> plz update and retry
👍
